version: '3.7'
services:
  todos-service:
    image: todos-service:latest
#    command: sh -c "sleep 1d" # for debug purposes
    restart: always
    networks:
      - mongodb_network
    ports:
      - 80:80
    environment:
      - LOGLEVEL=debug
      - APP_HOST=0.0.0.0
      - APP_PORT=80
      - DB_URL=mongodb://mongodb:27017

  mongodb:
    image : mongo
    container_name: mongodb
    networks:
      - mongodb_network
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/redbull/dev_sandbox/db/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped

networks:
  mongodb_network: